version: 2
jobs:
  build_maven:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout
      - run: mvn integration-test

  deploy_to_bintray:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout
      - run: mvn -B release:prepare -Dresume=false -DskipTests
      - run: mvn -s .circleci/setting.xml release:perform -DskipTests

    branches:
      only:
        - release

workflows:
  version: 2
  build:
    jobs:
      - build_maven
  deploy:
    jobs:
      - deploy_to_bintray
          filters:
            branches:
              only: master